import React from "react";
import { Table } from "antd";
import "./index.less";
import moment from 'moment'
const dataSource = 
[
    {
      "id": 464,
      "interviewerId": 3266,
      "name": "肖胜",
      "gender": 1,
      "mobile": 15911077226,
      "email": "hongyu.yang@zhaopin.com.cn",
      "company": "3",
      "examinerType": null,
      "interviewSituation": "2, 4",
      "interviewForm": "2, 3",
      "majorField": "1, 9, 4",
      "majorFieldDesc": null,
      "price": 0.00,
      "star": 3,
      "scheduleTaskId": null,
      "useType": "面试",
      "projectId": 1004156,
      "projectName": "劳务费全流程测试项目",
      "planDate": 1571875200000,
      "planTime": "19:55-20:55",
      "cityId": null,
      "cityName": "1",
      "universityName": "1",
      "campusName": "1",
      "placeName": "1",
      "taskStatus": 3,
      "modifyReason": null,
      "cancelReason": null,
      "createUserId": 8947,
      "createUserName": "王立军",
      "createTime": 1571918209035,
      "modifyUserId": 8947,
      "modifyUserName": "王立军",
      "modifyTime": 1571918209036,
      "isValid": 1,
      "details": null,
      "pageNumber": null,
      "pageSize": null,
      "userId": null,
      "dateRange": null,
      "cancelProjectIds": null,
      "invalidProjectIds": null,
      "planTimeList": null,
      "cost": {
        "id": 365,
        "interviewerScheduleId": 464,
        "interviewerId": 3266,
        "interviewerName": "肖胜",
        "star": 3,
        "isInner": 0,
        "scheduleTaskId": null,
        "useType": "面试",
        "projectId": 1004156,
        "projectName": "劳务费全流程测试项目",
        "planDate": 1571875200000,
        "costType": 0,
        "costAmount": 0.00,
        "finalAmount": 0.00,
        "taskStatus": 3,
        "payStatus": 1,
        "payee": "肖胜",
        "mobile": 15911077226,
        "identityCard": "110227199405211816",
        "bank": "建设银行(01050000)",
        "bankCardNumber": 6217000010011551000,
        "pushTime": null,
        "serialNumber": null,
        "paySubmitTime": null,
        "bankDealTime": null,
        "arriveTime": null,
        "payRemark": null,
        "failReason": null,
        "createUserId": 8947,
        "createUserName": "王立军",
        "createTime": 1571918340014,
        "modifyUserId": 8947,
        "modifyUserName": "王立军",
        "modifyTime": 1571918340014,
        "isValid": 1,
        "expectPayTime": null,
        "paySuccessTime": null,
        "pmName": null,
        "pmId": null,
        "cityName": null,
        "universityName": null,
        "campusName": null,
        "placeName": null,
        "financePayStatus": null,
        "evaluationBean": null,
        "serviceAmount": 0
      },
      "interviewer": null,
      "payStatus": null,
      "isInner": 0,
      "financePayStatus": 0
    },
    {
      "id": 45,
      "interviewerId": 3266,
      "name": "肖胜",
      "gender": 1,
      "mobile": 15911077226,
      "email": "hongyu.yang@zhaopin.com.cn",
      "company": "3",
      "examinerType": "1-3",
      "interviewSituation": "2, 4",
      "interviewForm": "2, 3",
      "majorField": "1, 9, 4",
      "majorFieldDesc": null,
      "price": 2.00,
      "star": 3,
      "scheduleTaskId": 50277,
      "useType": "面试",
      "projectId": 1004156,
      "projectName": "劳务费全流程测试项目",
      "planDate": 1566432000000,
      "planTime": "14:00-14:15",
      "cityId": null,
      "cityName": "北京",
      "universityName": "北京大学",
      "campusName": "本部",
      "placeName": "",
      "taskStatus": 3,
      "modifyReason": null,
      "cancelReason": null,
      "createUserId": 8947,
      "createUserName": "王立军",
      "createTime": 1566443020717,
      "modifyUserId": 8947,
      "modifyUserName": "王立军",
      "modifyTime": 1568284713386,
      "isValid": 1,
      "details": null,
      "pageNumber": null,
      "pageSize": null,
      "userId": null,
      "dateRange": null,
      "cancelProjectIds": null,
      "invalidProjectIds": null,
      "planTimeList": null,
      "cost": {
        "id": 103,
        "interviewerScheduleId": 45,
        "interviewerId": 3266,
        "interviewerName": "肖胜",
        "star": 3,
        "isInner": 0,
        "scheduleTaskId": 50277,
        "useType": "面试",
        "projectId": 1004156,
        "projectName": "劳务费全流程测试项目",
        "planDate": 1566432000000,
        "costType": 0,
        "costAmount": 2.00,
        "finalAmount": 2.02,
        "taskStatus": 3,
        "payStatus": 1,
        "payee": "肖胜",
        "mobile": 15911077226,
        "identityCard": "110227199405211816",
        "bank": "建设银行(01050000)",
        "bankCardNumber": 6217000010011550384,
        "pushTime": null,
        "serialNumber": null,
        "paySubmitTime": null,
        "bankDealTime": null,
        "arriveTime": null,
        "payRemark": null,
        "failReason": null,
        "createUserId": 8947,
        "createUserName": "王立军",
        "createTime": 1568284980017,
        "modifyUserId": 8947,
        "modifyUserName": "王立军",
        "modifyTime": 1568284980017,
        "isValid": 1,
        "expectPayTime": null,
        "paySuccessTime": null,
        "pmName": null,
        "pmId": null,
        "cityName": null,
        "universityName": null,
        "campusName": null,
        "placeName": null,
        "financePayStatus": null,
        "evaluationBean": null,
        "serviceAmount": 0
      },
      "interviewer": null,
      "payStatus": null,
      "isInner": 0,
      "financePayStatus": 0
    }
  ];

const columns = [
  {
    title: "面试官",
    dataIndex: "name",
    key: "name"
  }, {
    title: "面试日期",
    dataIndex: "planDate",
    key: "planDate",render(text,record,index){
        return text?moment(text).format('YYYY-MM-DD'):''
    }
  },
  {
    title: "学校",
    dataIndex: "universityName",
    key: "universityName"
  },
  {
    title: "面试官类型",
    dataIndex: "examinerType",
    key: "examinerType"
  },
  {
    title: "内外部员工",
    dataIndex: "isInner",
    key: "isInner"
  }, 
  {
    title: "星级",
    dataIndex: "star",
    key: "star"
  },
  {
    title: "任务状态",
    dataIndex: "taskStatus",
    key: "taskStatus"
  },
  {
    title: "支付状态",
    dataIndex: "payStatus",
    key: "payStatus"
  }
];
class Interviewer extends React.Component {
  render() {
    return (
      <div>
        <Table rowKey="id" dataSource={dataSource} columns={columns} pagination={false}/>

      </div>
    );
  }
}
export default Interviewer